src/Entity/Photo.php
<?php

namespace App\Entity;

use App\Repository\PhotoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PhotoRepository::class)]
class Photo
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\ManyToOne(inversedBy: 'photos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $uploaded_at = null;

    #[ORM\Column]
    private ?bool $is_public = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): static
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeImmutable
    {
        return $this->uploaded_at;
    }

    public function setUploadedAt(\DateTime $uploaded_at): static
    {
        $this->uploaded_at = \DateTimeImmutable::createFromMutable($uploaded_at);
    
        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->is_public;
    }

    public function setIsPublic(bool $is_public): static
    {
        $this->is_public = $is_public;

        return $this;
    }
}

src/Controller/MyController.php
<?php

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Photo;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use App\Service\PhotoVisibilityService;

/**
 * @IsGranted("ROLE_USER")
 */
class MyController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    #[Route('/my/photos', name: 'my_photos')]
    public function index()
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createAccessDeniedException('User is not authenticated');
        }

        $myPhotos = $this->entityManager->getRepository(Photo::class)->findBy(['user' => $user]);

        return $this->render('my/index.html.twig',[
            'myPhotos' => $myPhotos
        ]);
    }

    #[Route('/my/photos/set_visibility/{id}/{visibility}', name: 'my_photos_set_visibility')]
    public function myPhotoChangeVisibility(PhotoVisibilityService $photoVisibilityService, int $id, bool $visibility)
    {
        $messages = [
            '1' => ' to public',
            '0' => ' to private'
        ];
    
        if ($photoVisibilityService->makeVisible($id, $visibility)) {
            $this->addFlash('success', 'Visibility changed' . $messages[$visibility]);
        } else {
            $this->addFlash('error', 'You are not authorized to change visibility' . $messages[$visibility]);
        }
    
        return $this->redirectToRoute('my_photos');
    }

    #[Route('/my/photos/remove/{id}', name: 'my_photos_remove')]
    public function myPhotosRemove(int $id, EntityManagerInterface $entityManager, Filesystem $filesystem): Response
    {
        $myPhoto = $entityManager->getRepository(Photo::class)->find($id);

        if ($this->getUser() === $myPhoto->getUser()) {
            $filePath = 'image/hosting/' . $myPhoto->getFilename();
    
            if ($filesystem->exists($filePath)) {
                try {
                    $filesystem->remove($filePath);
                    $this->addFlash('success', 'File removed from disk');
                } catch (IOExceptionInterface $exception) {
                    $this->addFlash('error', 'Error removing photo: ' . $exception->getMessage());
                    return $this->redirectToRoute('latest_photos');
                }
            } else {
                $this->addFlash('error', 'File does not exist');
            }
    
            $entityManager->remove($myPhoto);
            $entityManager->flush();
            $this->addFlash('success', 'Photo removed from database');
        } else {
            $this->addFlash('error', 'You are not authorized to remove this photo');
        }

        return $this->redirectToRoute('my_photos');
    }
}

templates/my/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ parent() }} Strona główna{% endblock %}

{% block content %}
<div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
        <h1 class="mt-5 mb-4 h4">Najnowsze zdjęcia</h1>

        <div class="mt-5">
            <div class="row">
                {% for photo in myPhotos %}
                    <div class="col-sm-12 col-lg-4">
                        <div class="card-deck">
                            <div class="card d-flex justify-content-between">
                                <div class="imageGallery1">
                                    <a href="/images/hosting/{{ photo.filename}}"><img src="/images/hosting/{{ photo.filename}}" class="card-img-top" alt=""></a>
                                </div>
                                <div class="card-footer">
                                    <small class="text-muted">Wysłano: {{ photo.uploadedAt|date('d.m.Y H:i:s')}}</small>
                                    <small class="text-muted">Dodał: {{ photo.user.username}}</small>
                                    <p>
                                        {% if photo.user == app.user %}
                                            <a href="{{ path('my_photos_remove', {'id': photo.id}) }}" class="badge badge-danger">Usuń</a>   
                                            {% if photo.isPublic == '1' %}
                                                <a href="{{ path('my_photos_set_visibility', {'id': photo.id, 'visibility': '0'}) }}" class="badge badge-primary">Ustaw prywatne</a>
                                            {% else %}
                                                <a href="{{ path('my_photos_set_visibility', {'id': photo.id, 'visibility': '1'}) }}" class="badge badge-success">Ustaw publiczne</a>
                                            {% endif %}
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}